ingredientList = {
  feyberry : {
    name: 'Feyberry',
    A:6,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 6,
    price:4,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    areA:'enchanted_forest',
    img:'feyberry.png'
  },
  impstool_mushroom:{
    name: 'Impstool Mushroom',
    A:0,
    B:4,
    C:0,
    D:0,
    E:0,
    totalMagimins: 4,
    price:17,
    pallate:'neutral',
    stomach:'good',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'impstool_mushroom.png'
  },
  kappa_pheromones:{
    name: 'Kappa Pheromones',
    A:4,
    B:0,
    C:4,
    D:0,
    E:0,
    totalMagimins: 8,
    price:13,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'kappa_pheromones.png'
  },
  mandrake_root:{
    name: 'Mandrake Root',
    A:0,
    B:6,
    C:0,
    D:0,
    E:0,
    totalMagimins: 6,
    price:4,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'mandrake_root.png'
  },
  pixiedust_diamond:{
    name: 'Pixiedust Diamond',
    A:0,
    B:4,
    C:4,
    D:0,
    E:0,
    totalMagimins: 8,
    price:14,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'pixiedust_diamond.png'
  },
  river_calamari:{
    name: 'River Calamari',
    A:8,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 8,
    price:5,
    pallate:'neutral',
    stomach:'bad',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'river_calamari.png'
  },
  river_pixies_shell:{
    name: 'River-Pixies Shell',
    A:4,
    B:4,
    C:0,
    D:0,
    E:0,
    totalMagimins: 8,
    price:11,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'river_pixies_shell.png'
  },
  rotfly_larva:{
    name: 'Rotfly Larva',
    A:0,
    B:0,
    C:4,
    D:0,
    E:0,
    totalMagimins: 4,
    price:10,
    pallate:'good',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'rotfly_larva.png'
  },
  sack_of_slime:{
    name: 'Sack Of Slime',
    A:0,
    B:0,
    C:6,
    D:0,
    E:0,
    totalMagimins: 6,
    price:7,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'enchanted_forest',
    img:'sack_of_slime.png'
  },
  murkwater_pearl:{
    name: 'Murkwater Pearl',
    A:0,
    B:0,
    C:0,
    D:12,
    E:0,
    totalMagimins: 12,
    price:27,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'good',
    hear:'neutral',
    area:'mushroom_mire',
    img:'murkwater_pearl.png'
  },
  sack_of_hive_slime:{
    name: 'Sack Of Hive Slime',
    A:0,
    B:0,
    C:18,
    D:0,
    E:0,
    totalMagimins: 18,
    price:21,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'sack_of_hive_slime.png'
  },
  swamp_octopus:{
    name: 'Swamp Octpus',
    A:24,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 18,
    price:18,
    pallate:'neutral',
    stomach:'bad',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'swamp_octopus.png'
  },
  ghostlight_bloom:{
    name: 'Ghostlight Bloom',
    A:18,
    B:0,
    C:0,
    D:6,
    E:0,
    totalMagimins: 18,
    price:28,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'ghostlight_bloom.png'
  },
  swamp_fish:{
    name: 'Swamp Fish',
    A:12,
    B:0,
    C:0,
    D:6,
    E:0,
    totalMagimins: 18,
    price:22,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'swamp_fish.png'
  },
  horned_jelly:{
    name: 'Horned Jelly',
    A:18,
    B:0,
    C:0,
    D:6,
    E:0,
    totalMagimins: 18,
    price:20,
    pallate:'neutral',
    stomach:'bad',
    smell:'neutral',
    look:'good',
    hear:'neutral',
    area:'bone_wastes',
    img:'horned_jelly.png'
  },
  rotfly_cocoon:{
    name: 'Rotfly Cocoon',
    A:0,
    B:0,
    C:12,
    D:0,
    E:0,
    totalMagimins: 12,
    price:25,
    pallate:'good',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'rotfly_cocoon.png'
  },
  sphinx_flea:{
    name: 'Sphinx Flea',
    A:12,
    B:6,
    C:0,
    D:0,
    E:0,
    totalMagimins: 12,
    price:35,
    pallate:'neutral',
    stomach:'good',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'sphinx_flea.png'
  },
  salamanders_fiery_tongue:{
    name: 'Salamanders Fiery Tongue',
    A:0,
    B:24,
    C:0,
    D:0,
    E:0,
    totalMagimins: 24,
    price:22,
    pallate:'neutral',
    stomach:'neutral',
    smell:'bad',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'salamanders_fiery_tongue.png'
  },
  selkie_lice:{
    name: 'Selkie Lice',
    A:10,
    B:20,
    C:0,
    D:0,
    E:0,
    totalMagimins: 30,
    price:50,
    pallate:'neutral',
    stomach:'good',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'ocean_coasts',
    img:'selkie_lice.png'
  },
  figment_pomme:{
    name: 'Figment Pomme',
    A:0,
    B:18,
    C:6,
    D:0,
    E:0,
    totalMagimins: 24,
    price:26,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'figment_pomme.png'
  },
  barghast_canine:{
    name: 'Barghast Canine',
    A:0,
    B:30,
    C:0,
    D:0,
    E:10,
    totalMagimins: 40,
    price:55,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'shadow_steppe',
    img:'barghast_canine.png'
  },
  warg_pheromones:{
    name: 'Warg Pheromones',
    A:12,
    B:0,
    C:12,
    D:0,
    E:0,
    totalMagimins: 24,
    price:26,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'warg_pheromones.png'
  },
  warg_pheromones:{
    name: 'Warg Pheromones',
    A:12,
    B:0,
    C:12,
    D:0,
    E:0,
    totalMagimins: 24,
    price:26,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'warg_pheromones.png'
  },
  trollstool_mushroom:{
    name: 'Trollstol Mushroom',
    A:0,
    B:12,
    C:0,
    D:0,
    E:0,
    totalMagimins: 12,
    price:20,
    pallate:'neutral',
    stomach:'good',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'trollstool_mushroom.png'
  },
  puckberry:{
    name: 'Puckberry',
    A:18,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 18,
    price:16,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'puckberry.png'
  },
  wraith_orchid:{
    name: 'Wraith Orchid',
    A:0,
    B:0,
    C:0,
    D:12,
    E:0,
    totalMagimins: 12,
    price:19,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'wraith_orchid.png'
  },
  qilins_trihorn:{
    name: 'Qilins Tri-Horn',
    A:0,
    B:0,
    C:24,
    D:0,
    E:0,
    totalMagimins: 24,
    price:18,
    pallate:'bad',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'qilins_tri-horn.png'
  },
  mote_of_mana:{
    name: 'Mote Of Mana',
    A:15,
    B:15,
    C:15,
    D:15,
    E:15,
    totalMagimins: 75,
    price:130,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'shadow_steppe',
    img:'mote_of_mana.png'
  },
  misma_spore:{
    name: 'Miasma Spore',
    A:0,
    B:18,
    C:0,
    D:6,
    E:0,
    totalMagimins: 24,
    price:30,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'misma_spore.png'
  },
  fairy_flower_bud:{
    name: 'Fairy Flower Bud',
    A:12,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 12,
    price:23,
    pallate:'neutral',
    stomach:'neutral',
    smell:'good',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'fairy_flower_bud.png'
  },
  ravens_shadow:{
    name: 'Fairy Flower Bud',
    A:0,
    B:10,
    C:12,
    D:18,
    E:0,
    totalMagimins: 40,
    price:52,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'mushroom_mire',
    img:'ravens_shadow.png'
  },
  desert_metal:{
    name: 'Desert Metal',
    A:0,
    B:12,
    C:0,
    D:0,
    E:0,
    totalMagimins: 12,
    price:25,
    pallate:'neutral',
    stomach:'good',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'desert_metal.png'
  },
  golems_eye_diamond:{
    name: "Golem's-Eye Diamond",
    A:0,
    B:12,
    C:12,
    D:0,
    E:0,
    totalMagimins: 24,
    price:28,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'golems-eye_diamond.png'
  },
  fulgurite_ore:{
    name: "Golem's-Eye Diamond",
    A:0,
    B:0,
    C:0,
    D:30,
    E:0,
    totalMagimins: 30,
    price:40,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'fulgurite_ore.png'
  },
  dropspiders_shadow:{
    name: "Dropspider's Shadow",
    A:0,
    B:0,
    C:30,
    D:20,
    E:10,
    totalMagimins: 60,
    price:90,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'shadow_steppe',
    img:'dropspiders_shadow.png'
  },
  giantstool_mushroom:{
    name: "Giantstool Mushroom",
    A:0,
    B:20,
    C:0,
    D:0,
    E:0,
    totalMagimins: 20,
    price:40,
    pallate:'neutral',
    stomach:'good',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'giantstool_mushroom.png'
  },
  antlered_jelly:{
    name: "Antlered Jelly",
    A:30,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 30,
    price:28,
    pallate:'neutral',
    stomach:'bad',
    smell:'neutral',
    look:'good',
    hear:'neutral',
    area:'storm_plains',
    img:'antlered_jelly.png'
  },
  rotfly_adult:{
    name: "Rotfly Adult",
    A:0,
    B:0,
    C:20,
    D:0,
    E:0,
    totalMagimins: 20,
    price:38,
    pallate:'good',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'ocean_coasts',
    img:'rotfly_adult.png'
  },
  saltwatermelon:{
    name: "Saltwatermelon",
    A:0,
    B:0,
    C:0,
    D:40,
    E:0,
    totalMagimins: 40,
    price:44,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'bad',
    hear:'neutral',
    area:'ocean_coasts',
    img:'saltwatermelon.png'
  },
  electrocution_eel:{
    name: "Electrocution Eel",
    A:10,
    B:10,
    C:10,
    D:0,
    E:0,
    totalMagimins: 30,
    price:45,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'good',
    hear:'neutral',
    area:'storm_plains',
    img:'electrocution_eel.png'
  },
  thunderbirds_molted_feather:{
    name: "Thunderbird's Molted Feather",
    A:0,
    B:0,
    C:30,
    D:0,
    E:10,
    totalMagimins: 40,
    price:60,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'thunderbirds_molted_feather.png'
  },
  copper_dollop:{
    name: "Copper Dollop",
    A:15,
    B:15,
    C:15,
    D:15,
    E:0,
    totalMagimins: 60,
    price:95,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'copper_dollop.png'
  },
  static_spiderling:{
    name: "Static Spiderling",
    A:0,
    B:0,
    C:0,
    D:0,
    E:30,
    totalMagimins: 30,
    price:50,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'bad',
    hear:'good',
    area:'storm_plains',
    img:'static_spiderling.png'
  },
  spriggan_antler:{
    name: "Spriggan Antler",
    A:0,
    B:0,
    C:40,
    D:0,
    E:0,
    totalMagimins: 40,
    price:38,
    pallate:'bad',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'spriggan_antler.png'
  },
  reef_radish:{
    name: "Reef Radish",
    A:0,
    B:30,
    C:0,
    D:0,
    E:0,
    totalMagimins: 30,
    price:32,
    pallate:'bad',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'good',
    area:'ocean_coasts',
    img:'reef_radish.png'
  },
  boogeyberry:{
    name: "Boogeyberry",
    A:30,
    B:0,
    C:0,
    D:0,
    E:0,
    totalMagimins: 30,
    price:30,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'boogeyberry.png'
  },
  slapping_turtles_shell:{
    name: "Slapping Turtle's Shell",
    A:20,
    B:20,
    C:0,
    D:0,
    E:0,
    totalMagimins: 40,
    price:46,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'slapping_turtles_shell.png'
  },
  leech_snails_shell:{
    name: "Leech Snail's Shell",
    A:12,
    B:12,
    C:0,
    D:0,
    E:0,
    totalMagimins: 24,
    price:26,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'leech_snails_shell.png'
  },
  glass_ore:{
    name: "Glass Ore",
    A:0,
    B:0,
    C:0,
    D:18,
    E:0,
    totalMagimins: 18,
    price:24,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'glass_ore.png'
  },
  sack_of_composite_slime:{
    name: "Sack Of Composite Slime",
    A:0,
    B:0,
    C:30,
    D:0,
    E:0,
    totalMagimins: 30,
    price:36,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'shadow_steppe',
    img:'sack_of_composite_slime.png'
  },
  fire_flower:{
    name: "Fire Flower",
    A:40,
    B:0,
    C:0,
    D:20,
    E:0,
    totalMagimins: 60,
    price:55,
    pallate:'neutral',
    stomach:'neutral',
    smell:'bad',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'fire_flower.png'
  },
  raiju_droppings:{
    name: "Fire Flower",
    A:30,
    B:0,
    C:0,
    D:10,
    E:0,
    totalMagimins: 40,
    price:55,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'raiju_droppings.png'
  },
  golemite:{
    name: "Golemite",
    A:18,
    B:12,
    C:0,
    D:10,
    E:0,
    totalMagimins: 40,
    price:38,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'bone_wastes',
    img:'golemite.png'
  },
  mandragon_root:{
    name: "Mandragon Root",
    A:0,
    B:30,
    C:0,
    D:0,
    E:0,
    totalMagimins: 30,
    price:34,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'ocean_coasts',
    img:'mandragon_root.png'
  },
  hallucinatory_shroom:{
    name: "Mandragon Root",
    A:0,
    B:0,
    C:30,
    D:0,
    E:0,
    totalMagimins: 30,
    price:36,
    pallate:'good',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'bad',
    area:'shadow_steppe',
    img:'hallucinatory_shroom.png'
  },
  spiders_bait_diamond:{
    name: "Spider's-Bait Diamond",
    A:0,
    B:20,
    C:20,
    D:0,
    E:0,
    totalMagimins: 40,
    price:50,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'shadow_steppe',
    img:'spiders_bait_diamond.png'
  },
  thunder_quartz:{
    name: "Mandragon Root",
    A:30,
    B:10,
    C:20,
    D:0,
    E:0,
    totalMagimins: 60,
    price:72,
    pallate:'neutral',
    stomach:'neutral',
    smell:'neutral',
    look:'neutral',
    hear:'neutral',
    area:'storm_plains',
    img:'thunder_quartz.png'
  }
}


class Ingredients {
  
  getIngredients(filter) {
    var activeFilters = [];
    let anyMatch = false;
    Object.keys(filter).map((index) => {
      if(filter[index] !== '0' && filter[index] !== 'neutral') {
        activeFilters[index] = filter[index];
        anyMatch = true;
      }
    });
    if(!anyMatch){
      return ingredientList;
    }
    let filteredList = {};
    
    Object.keys(ingredientList).map((index) => {
      let match = false;
      let ingredient = ingredientList[index]
      Object.keys(activeFilters).map((e) => {
        match = ingredient[e] == activeFilters[e]
      });
      if(match) {
        filteredList[index] = ingredient
      }
    });
    return filteredList;
  }


  getOnlyIngredientsWith(values) {
    let filteredList = [];
    Object.keys(ingredientList).forEach((ingredientName,i)=>{
      let match = false;
      values.forEach((value)=>{
        if(!match)
          match = ingredientList[ingredientName][value] > 0;
      }); 
      if(match)
        filteredList.push(ingredientList[ingredientName])
    });
    return filteredList;
  }

}

var ing = new Ingredients();

module.exports = ing;

